### ISSUE TITLE
Unable to run the language client server.

### ISSUE THREAD

**Issue by thyrgle** [leanprover/lean.vim#1]
Hello,

I tried following the instructions to install the `lean-language-server` porition. Unfortunately, I ran into some issues.

- I successfully installed `lean-language-server` using `npm install -g lean-language-server`.
- I then used the neovim plugin:

```Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }

let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {
    \ 'lean': ['lean-language-server', '--stdio'],
    \ }

nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
```

I was unable to run, so I tried changing:

```nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
```

To:

```nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
```

Since that looked more like what the `LanguageClient-neovim` uses. Still didn't work. There were issues executing the `lean-language-server` executable. So I ended up modifying `/usr/local/bin/lean-language-server` which originally started with `"use strict";` to:

```
#!/usr/bin/env node
"use strict";
```

Which fixed some errors, however, when I press `K` or `gd` I get:

```
{"jsonrpc": "2.0", "id": 1, "error": {"code": -32603, "...r failed unexpectedly without providing any details."}}
```

Any help solving this issue would be appreciated. Thank you.

**Comment by thyrgle** [comment]
Wait, my bad, I made some mistakes with my Lean installation... Although, I am going to check about the shebang by reinstalling stuff.

**Comment by thyrgle** [comment]
Ok, the real problem for me was actually `lean-language-server`. I created a pull request [here](https://github.com/leanprover/lean-client-js/pull/4) to fix the issue with installation.

**Comment by gebner** [comment]
Ok, the referenced PR has been merged so I'll close this issue.  Feel free to reopen if the issue persists.
