### ISSUE TITLE
list-like attribute "arguments" are mishilighted / terminate the attributes

### ISSUE THREAD

**Issue by Julian** [leanprover/lean.vim#15]
This may be too much of an edge case to care about at this point even though it seems there are a decent number of instances in mathlib, but:

```lean
@[derive [foo, bar]] def quux := 7
```

terminates the attributes list at the first `]`.

vscode-lean seems to do the same.

**Comment by gebner** [comment]
Fixed. :smile:

**Comment by Julian** [comment]
Pfffffft nice.
