### ISSUE TITLE
Nested comments are mishilighted

### ISSUE THREAD

**Issue by Julian** [leanprover/lean.vim#5]
(This is probably a note-to-self, I'll try to fix at some point)

E.g. the following is mishilighted:

```

/-
/-- The `set` of `legal` moves from a given square. -/
lemma moves_from_def (pos : m × n) :
  b.moves_from pos = {x : move.legal b | x.start_square = pos}.to_finset := rfl
-/

```

where the entire docstring + lemma is commented out.

**Comment by gebner** [comment]
Fixed by 703de13461051a13f46bc83c5deb13b4172407d8
