### ISSUE TITLE
[Request] Unicode support or mapping

### ISSUE THREAD

**Issue by yushangakki** [leanprover/lean.vim#6]
Great language and plugin!

However, some unicodes are supported by vim (like right arrow), while some are not (the real number field). Is there any support that helps with that (like mapping \R to Real numbers)? Thanks!

If that works for you I can start a pull request

**Comment by gebner** [comment]
There is PR #3, which adds some hand-picked abbreviations.  Ideally, we would automatically generate them from the [official list](https://github.com/leanprover/vscode-lean/blob/master/translations.json).

**Comment by yushangakki** [comment]
Cool, thanks!

**Comment by Julian** [comment]
I have a version that does that if that helps you.

It's here: https://github.com/Julian/lean-unicode.vim/ and is what I use.

**Comment by Julian** [comment]
(They're indeed autogenerated from the official list.)

**Comment by yushangakki** [comment]
It works (though I don't understand why you put parentheses around the snippet trigger), thank you very much!

**Comment by Julian** [comment]
Sorry which snippet trigger? But yeah happy to see PRs there certainly if something doesn't work the way you'd like, though yeah for me it does -- I hit \a<tab> and I get alpha, etc.
