### ISSUE TITLE
Implement opt-in invocation of leanproject

### ISSUE THREAD

**Issue by Julian** [leanprover/lean.vim#7]
The equivalent of  leanprover/vscode-lean#228 -- something like (pseudocodeish):

```
if g:lean_autofetch_mathlib
    autocmd! BufReadPost *.lean lean#check_mathlib(get(g, "lean_leanproject_host", "leanproject"))
endif
```

where `lean#check_mathlib` runs `leanproject get-mathlib-cache` when needed.

**Comment by gebner** [comment]
This should be done in https://github.com/Julian/lean.nvim/ (if at all, since this is gonna change in Lean 4).

**Comment by Julian** [comment]
Sounds good, will close this here then, we can decide later on doing it in there instead but I don't care too much about this functionality personally.
